M48
; DRILL file {KiCad 9.0.1} date 2025-04-09T09:21:16+0800
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2025-04-09T09:21:16+08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.1
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0256
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0390
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C0.0510
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T4C0.0630
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T5C0.0709
%
G90
G05
T1
X3.2862Y-3.1642
X3.2862Y-3.3917
T2
X4.9445Y-2.2328
X4.9445Y-2.3128
X5.1445Y-2.2728
T3
X5.1679Y-5.1363
T4
X3.2413Y-2.6378
T5
X3.4185Y-2.6378
M30
